# Generated by Django 3.0.7 on 2020-06-24 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200624_0601'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='slug',
            field=models.SlugField(default='dummy'),
            preserve_default=False,
        ),
    ]
