# Generated by Django 3.0.7 on 2020-06-24 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_comment_slug'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
